### ISSUE TITLE
Could you please add 'Fold all of indentation level' 4 and 5?

### ISSUE THREAD

**Issue by hyperphysin** [masaki39/outline-converter#1]
I find 'Fold all of indentation level' very useful.

Could you please add 'Fold all of indentation level' 4 and 5?

**Comment by masaki39** [comment]
Please update to 1.3.1.

[Release 1.3.1 · masaki39/outline-converter](https://github.com/masaki39/outline-converter/releases/tag/1.3.1)

**Comment by hyperphysin** [comment]
Thanks a lot. It works perfectly.

**Comment by hyperphysin** [comment]
Why don't you make the folding function a separate plugin?
It's super useful and it's a shame that ppl would not know that this plugin has the function.

**Comment by masaki39** [comment]
Thank you. However, I am not a programmer, and I am busy, so I don't want to increase my workload.
If others have the same request as well, I will consider it.
